# Generated by Django 3.0.3 on 2020-02-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='trsackName',
            new_name='trackName',
        ),
    ]
